import {
    DashboardOutlined,
    SnippetsOutlined,
    ShoppingCartOutlined,
    UserOutlined,
    GiftOutlined,
    UsergroupAddOutlined,
    ShopOutlined,
    ShoppingOutlined,
    MobileOutlined,
    SettingOutlined,
    FileTextOutlined,
    MailOutlined,
    PictureOutlined,
} from "@ant-design/icons";
import { APP_PREFIX_PATH } from "configs/AppConfig";

const mainNavTree = [
    {
        key: "main",
        path: `${APP_PREFIX_PATH}/main`,
        title: "Основные",
        icon: "",
        breadcrumb: false,
        submenu: [
            {
                key: "main-dashboards",
                path: `${APP_PREFIX_PATH}/main/dashboards`,
                title: "Дашборд",
                icon: DashboardOutlined,
                breadcrumb: false,
                submenu: [],
            },
            {
                key: "main-scheduler",
                path: `${APP_PREFIX_PATH}/main/scheduler`,
                title: "Планировщик",
                icon: SnippetsOutlined,
                breadcrumb: false,
                submenu: [],
            },
            {
                key: "main-catalog",
                path: `${APP_PREFIX_PATH}/main/catalog`,
                title: "Каталог",
                icon: ShoppingCartOutlined,
                breadcrumb: false,
                submenu: [
                    {
                        key: "main-catalog-goods",
                        path: `${APP_PREFIX_PATH}/main/catalog/goods`,
                        title: "Товары",
                        icon: "",
                        breadcrumb: false,
                        submenu: [],
                    },
                    {
                        key: "main-catalog-сategories",
                        path: `${APP_PREFIX_PATH}/main/catalog/сategories`,
                        title: "Категории",
                        icon: "",
                        breadcrumb: false,
                        submenu: [],
                    },
                    {
                        key: "main-catalog-collections",
                        path: `${APP_PREFIX_PATH}/main/catalog/collections`,
                        title: "Коллекции",
                        icon: "",
                        breadcrumb: false,
                        submenu: [],
                    },
                    {
                        key: "main-catalog-combo",
                        path: `${APP_PREFIX_PATH}/main/catalog/сombo`,
                        title: "Комбо",
                        icon: "",
                        breadcrumb: false,
                        submenu: [],
                    },
                ],
            },

            {
                key: "main-orders",
                path: `${APP_PREFIX_PATH}/main/orders`,
                title: "Заказы",
                icon: ShoppingOutlined,
                breadcrumb: false,
                submenu: [],
            },
            {
                key: "main-clients",
                path: `${APP_PREFIX_PATH}/main/clients`,
                title: "Клиенты",
                icon: UserOutlined,
                breadcrumb: false,
                submenu: [
                    {
                        key: "main-clients-list",
                        path: `${APP_PREFIX_PATH}/main/clients/list`,
                        title: "Список клиентов",
                        icon: "",
                        breadcrumb: false,
                        submenu: [],
                    },
                    {
                        key: "main-clients-groups",
                        path: `${APP_PREFIX_PATH}/main/clients/groups`,
                        title: "Группы клиентов",
                        icon: "",
                        breadcrumb: false,
                        submenu: [],
                    },
                ],
            },
            {
                key: "main-banners",
                path: `${APP_PREFIX_PATH}/main/banners`,
                title: "Банеры",
                icon: PictureOutlined,
                breadcrumb: false,
                submenu: [],
            },
            {
                key: "main-promo",
                path: `${APP_PREFIX_PATH}/main/promo`,
                title: "Промокоды",
                icon: GiftOutlined,
                breadcrumb: false,
                submenu: [],
            },
            {
                key: "main-shops",
                path: `${APP_PREFIX_PATH}/main/shops`,
                title: "Оффлайн точки",
                icon: ShopOutlined,
                breadcrumb: false,
                submenu: [
                    {
                        key: "main-shops-address",
                        path: `${APP_PREFIX_PATH}/main/shops/address`,
                        title: "Адреса",
                        icon: "",
                        breadcrumb: false,
                        submenu: [],
                    },
                    {
                        key: "main-shops-areas",
                        path: `${APP_PREFIX_PATH}/main/shops/areas`,
                        title: "Геозоны",
                        icon: "",
                        breadcrumb: false,
                        submenu: [],
                    },
                ],
            },
            {
                key: "main-staff",
                path: `${APP_PREFIX_PATH}/main/staff`,
                title: "Сотрудники",
                icon: UsergroupAddOutlined,
                breadcrumb: false,
                submenu: [],
            },
            {
                key: "main-newsletters",
                path: `${APP_PREFIX_PATH}/main/newsletters`,
                title: "Рассылки",
                icon: MailOutlined,
                breadcrumb: false,
                submenu: [],
            },
        ],
    },
];
const systemNavTree = [
    {
        key: "system",
        path: `${APP_PREFIX_PATH}/system`,
        title: "Системные",
        icon: "",
        breadcrumb: false,
        submenu: [
            {
                key: "settings",
                path: `${APP_PREFIX_PATH}/system/settings`,
                title: "Настройки",
                icon: SettingOutlined,
                breadcrumb: false,
                submenu: [],
            },
            {
                key: "mobile",
                path: `${APP_PREFIX_PATH}/system/mobile`,
                title: "Мобильное приложение",
                icon: MobileOutlined,
                breadcrumb: false,
                submenu: [],
            },
            {
                key: "logs",
                path: `${APP_PREFIX_PATH}/system/logs`,
                title: "Логи",
                icon: FileTextOutlined,
                breadcrumb: false,
                submenu: [],
            },
        ],
    },
];

const navigationConfig = [...mainNavTree, ...systemNavTree];

export default navigationConfig;
