export const SET_ELEMENTS = "SET_ELEMENTS";
export const SET_DRAGGED_ELEMENT = "SET_DRAGGED_ELEMENT";
export const SET_DOWNLOAD_DATA = "SET_DOWNLOAD_DATA";
export const ADD_BOARD_ELEMENTS = "ADD_BOARD_ELEMENTS";
export const UPDATE_BOARD_ELEMENTS = "UPDATE_BOARD_ELEMENTS";
export const CLEANUP_BOARD_ELEMENTS = "CLEANUP_BOARD_ELEMENTS";
export const CLEANUP = "CLEANUP";
